[versions]
kotlin = "2.2.21"
kotest = "6.0.5"

shadow = "9.2.2"
dokka = "2.1.0"
jreleaser = "1.21.0"

[libraries]
kotest-core = { group = "io.kotest", name = "kotest-assertions-core", version.ref = "kotest" }
kotest-junit = { group = "io.kotest", name = "kotest-runner-junit5", version.ref = "kotest" }

plugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
plugin-shadow = { module = "com.gradleup.shadow:shadow-gradle-plugin", version.ref = "shadow" }
plugin-jreleaser = { module = "org.jreleaser:org.jreleaser.gradle.plugin", version.ref = "jreleaser" }
plugin-dokka = { module = "org.jetbrains.dokka:org.jetbrains.dokka.gradle.plugin", version.ref = "dokka" }

[bundles]
test = ["kotest-core", "kotest-junit"]